# Generated by Django 4.2 on 2026-04-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseassignment',
            name='target_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='medical_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
